### ISSUE TITLE
Arm32 support

### ISSUE THREAD

**Issue by charsleysa** [UltraOS/Hyper#57]
Hi there,

Are there any plans to support Arm32?

**Comment by 8infy** [comment]
> Hi there,
> 
> Are there any plans to support Arm32?

Hey there! I guess it is something I would like to support eventually, however, right now I have other things to work on that are more important.

The way the project is currently structured is with a lot of assumptions that `UEFI == 64 bit`. So it would require a bit of effort to get rid of those assumptions. Since i686 is supported already, 32 bit arm probably wouldn't be too much extra work.

**Comment by PC-Doctor666** [comment]
Ballsack
